### ISSUE TITLE
File Permission Denied Error on Mac

### ISSUE THREAD

**Issue by 1schlick** [JoshuaMKW/pyiiasmh#1]
<img width="494" alt="Screenshot 2023-07-02 at 1 52 41 PM" src="https://github.com/JoshuaMKW/pyiiasmh/assets/53189655/939fbadd-d8cd-497e-9d73-85e45b868b5d">

I pasted someone else's uncompiled code into the left box, then clicked the right arrow. As you can see, I get the error that the script is unable to access a certain file. How do I workaround this?

I already tried running chmod a+x on the script and also chmod +x.

**Comment by JoshuaMKW** [comment]
The problem is that you haven't enabled execution permissions for the files in `k/python3.8/lib/darwin/powerpc-eabi-as/`. Try giving yourself those perms and try again.

**Comment by 1schlick** [comment]
Okay I tried running chmod -R o-rwx on the directory (which should give permissions to all files in that directory and all of it's sub-directories) and then running the script again and it still didn't work.

**Comment by 1schlick** [comment]
Okay I tried running chmod -R ugo+rwx on the directory and that seemed to work, but now I'm getting another error.
<img width="493" alt="Screenshot 2023-07-02 at 2 35 22 PM" src="https://github.com/JoshuaMKW/pyiiasmh/assets/53189655/18ddf63d-94a9-46bb-b77c-f186ceec2903">

**Comment by JoshuaMKW** [comment]
That's something I haven't seen before. I think it might be that the libs simply aren't compatible with your setup.

You could possibly try CodeWrite as an alternative but otherwise I'd suggest trying to compile it on another OS/PC.

**Comment by 1schlick** [comment]
I think the issue is that the libs aren't compiled for Mac and they are 32 bit. Is there anywhere where the libs are compiled for Mac? Or is the source code for those libs available? Then I might be able to compile it for Mac.

Also I have tried running CodeWrite using wine but it's not working.

**Comment by JoshuaMKW** [comment]
It being 32bit shouldn't be a problem, as typically a 64bit machine can run 32bit programs.

As for the ability to compile them, the binaries pyiiasmh uses were pre-compiled by someone else and I don't know where the source code is. I might have seen it once or twice before but your best bet would be to search for something like `powerpc-eabi-as source code`.
